#!/bin/sh
### ====================================================================== ###
##                                                                          ##
##  lyfi Bootstrap Script                                                  ##
##                                                                          ##
### ====================================================================== ###

warn() {
    echo "${PROGNAME}: $*"
}

die() {
    warn $*
    exit 1
}


DIRNAME="$(pwd)"
CONSOLEJAR="$DIRNAME/lyfi_0-5.jar"

# Setup the classpath
if [ ! -f "$CONSOLEJAR" ]; then
    die "Missing required file: $CONSOLEJAR please run the ant script, place the runnable lyfi jar file on $DIRNAME or edit the lyfi script and change the \$CONSOLEJAR variable to the jar file's full path"
fi

# Setup the JVM
if [ "x$JAVA" = "x" ]; then
    if [ "x$JAVA_HOME" != "x" ]; then
	JAVA="$JAVA_HOME/bin/java"
    else
	JAVA="java"
    fi
fi

# Execute the JVM in the foreground
      "$JAVA" $JAVA_OPTS \
         -jar "$CONSOLEJAR" "$@"
